### ISSUE TITLE
ir not working in lineage-15.1

### ISSUE THREAD

**Issue by mparus** [HyperTeam/android_device_xiaomi_santoni#1]
07-04 12:13:48.206  1111 13935 E ConsumerIrService: Error transmitting: -1
07-04 12:13:48.203   493   493 W ir@1.0-service: type=1400 audit(0.0:3001): avc: denied { search } for name="leds" dev="sysfs" ino=17449 scontext=u:r:hal_ir_default:s0 tcontext=u:object_r:sysfs_leds:s0 tclass=dir permissive=0

**Comment by karthick111** [comment]
Will be fixed
Anything not working?

**Comment by chaubeyprateek** [comment]
Will be fixed.. Anything else not working?

**Comment by mparus** [comment]
Still BT headset :(
Earlier I fix this bug - https://github.com/mparus/android_device_xiaomi_msm8937-common/commit/8f355d5c6b7d96ec9f370397e213d3b12f69da34

**Comment by chaubeyprateek** [comment]
common tree will be force pushed again.... its fixed there

**Comment by mparus** [comment]
I build rom and sync repo yesterday, BT headset still not working.

**Comment by karthick111** [comment]
It will be force pushed again wait for a while.

**Comment by mparus** [comment]
IR working after add this lines to sepolicy, example in file hal_ir_default.te

allow hal_ir_default sysfs_leds:dir search;
allow hal_ir_default sysfs:file { open read write };
